[package]
name = "h2-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
hyper = { version = "0.14.25", features = ["client", "server", "http2", "tcp"] }
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16" }
futures = "0.3.21"
